name: air_cli
description: The official CLI for the Air Framework. Streamline your Flutter development with modular architecture, automated code generation, and scalable state management.
version: 1.0.0
repository: https://github.com/AndreyDAraya/air-cli
environment:
  sdk: ^3.10.7

executables:
  air: air

dependencies:
  args: ^2.4.0
  path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
